name: Test Keyless Authentication with Cloud Build

on:
  push:
    branches:
    - main

jobs:
  cloud-build:
    name: Authenticate and Build
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    # checkout MUST come before auth
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    # reference: https://github.com/google-github-actions/auth
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        create_credentials_file: true
        access_token_lifetime: '100s'
        workload_identity_provider: ${{ secrets.PROVIDER_NAME }}
        service_account: ${{ secrets.SA_EMAIL }}

    - name: Set up Cloud SDK
      id: setup
      uses: google-github-actions/setup-gcloud@v1

    - name: Authenticate using credentials file
      run: gcloud auth login --cred-file=${{ steps.auth.outputs.credentials_file_path }}

    # the actual name of the SA might be redacted as *** as GitHub recognizes it as a secret
    - name: Confirm Cloud SDK runs as expected SA
      id: confirm
      run: gcloud info; gcloud auth list

    # only when token_format is access_token
    - name: List buckets
      run: |-
        curl -X GET \
          https://storage.googleapis.com/storage/v1/b?project=${{ secrets.PROJECT_ID }} \
          --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}"

    - name: Trigger build on Cloud Build
      id: build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "europe-west9-docker.pkg.dev/${{ secrets.PROJECT_ID }}/docker/quickstart-image:$GITHUB_SHA"
